language: python

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install coverage coveralls
  - pip install -e .

script:
  - coverage run setup.py test
  - coverage report

after_success: coveralls
